# -*- coding: utf-8 -*-
"""Netflix_DataAnalysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W4N-X1iv_QMLb2exaYvp4GDLsgI4Yobd

# Task
Analyze the Netflix content data from `netflix1.csv` by performing data cleaning and preparation (handling missing values, duplicates, and converting 'duration' to numerical format), then analyze content type distribution, temporal trends of content additions, investigate content ratings, and identify the top genres, countries, and directors. Finally, summarize the key insights.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
Netflix_data = pd.read_csv('netflix1.csv')
print(Netflix_data.head())

# Convert date column into datetime format
Netflix_data['date_added'] = pd.to_datetime(Netflix_data['date_added'], errors='coerce')
print("First 5 rows of 'date_added' after conversion:")
print(Netflix_data['date_added'].head())

# Check for any dates that couldn't be parsed
malformed_dates = Netflix_data[Netflix_data['date_added'].isna()]['date_added']
if not malformed_dates.empty:
    print("\nDates that could not be parsed:")
    print(malformed_dates)
else:
    print("\nAll dates were successfully parsed to datetime format.")

# Describe the data
print(Netflix_data.describe())
print('-------------------------------------------------------------------------------------------------------------------------------')
print(Netflix_data.info())

"""## Data Cleaning and Preparation


Address any remaining missing values, check for duplicate entries, and further process the 'duration' column to convert it into a numerical format (e.g., minutes for movies, seasons for TV shows) for better analysis.

"""

print("Missing values before cleaning:")
print(Netflix_data.isnull().sum())

print("Number of duplicate rows before dropping:", Netflix_data.duplicated().sum())
Netflix_data.drop_duplicates(inplace=True)
print("Number of duplicate rows after dropping:", Netflix_data.duplicated().sum())

# Process the 'duration' column by splitting it into numerical value and unit components.

Netflix_data[['duration_value', 'duration_unit']] = Netflix_data['duration'].str.split(' ', expand=True)
Netflix_data['duration_value'] = pd.to_numeric(Netflix_data['duration_value'])
print(Netflix_data[['duration', 'duration_value', 'duration_unit']].head())

"""## Analyze Content Type Distribution

Calculate and visualize the proportion of Movies versus TV Shows in the dataset using a pie chart to understand the content balance.

"""

# First step is get value counts for content type distribution and then visualize it using pie chart.
content_type_distribution = Netflix_data['type'].value_counts()
print(content_type_distribution)

plt.figure(figsize=(8, 8))
plt.pie(content_type_distribution, labels=content_type_distribution.index, autopct='%1.1f%%', startangle=90, colors=['#ff9999','#66b3ff'])
plt.title('Distribution of Content Types on Netflix')
plt.axis('equal') # Equal aspect ratio ensures that pie is drawn as a circle.
plt.show()

"""## Explore Temporal Trends


Analyze and visualize how the number of titles added to Netflix has changed over the years ('year_added').

**Reasoning**:
The first step in analyzing temporal trends is to extract the year from the 'date_added' column, which is currently in datetime format, and store it in a new column named 'year_added' for easier analysis and plotting.
"""

Netflix_data['year_added'] = Netflix_data['date_added'].dt.year
print(Netflix_data[['date_added', 'year_added']].head())

# Count the number of titles added each year to analyze the trend of content additions over time.
titles_added_per_year = Netflix_data['year_added'].value_counts().sort_index()
print("Titles added per year:")
print(titles_added_per_year.head())

# Visualize titles added per year
plt.figure(figsize=(12, 6))
plt.plot(titles_added_per_year.index, titles_added_per_year.values, marker='o', linestyle='-')
plt.title('Number of Titles Added to Netflix Over Time')
plt.xlabel('Year Added')
plt.ylabel('Number of Titles Added')
plt.grid(True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## Investigate Content Ratings

Examine the distribution of content ratings and consider how different ratings are distributed across content types (Movies vs. TV Shows). Visualize this using count plots.

**Reasoning**:
The first step in investigating content ratings is to calculate the overall distribution of ratings by counting the occurrences of each unique value in the 'rating' column. This will provide the data needed for the first visualization.
"""

# Calculate the overall distribution of ratings
rating_distribution = Netflix_data['rating'].value_counts()
print("Overall Distribution of Content Ratings:")
print(rating_distribution)

# Visualize this distribution using a count plot to clearly show the frequency of each rating category.
plt.figure(figsize=(12, 6))
sns.countplot(x='rating', data=Netflix_data, order=rating_distribution.index, palette='viridis', hue='rating', legend=False)
plt.title('Overall Distribution of Content Ratings on Netflix')
plt.xlabel('Content Rating')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# The next step is to visualize how these ratings are distributed across different content types (Movies vs. TV Shows)

plt.figure(figsize=(14, 7))
sns.countplot(x='rating', hue='type', data=Netflix_data, order=rating_distribution.index, palette='deep')
plt.title('Content Ratings Distribution by Type (Movies vs. TV Shows)')
plt.xlabel('Content Rating')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45, ha='right')
plt.legend(title='Content Type')
plt.tight_layout()
plt.show()

"""## Identify Top Genres, Countries, and Directors


For 'listed_in', 'country', and 'director' columns, extract and count the most frequent entries. Given that 'listed_in' and 'country' can contain multiple values, split these entries and count individual categories. Visualize the top N (e.g., top 10) for each category using bar charts.

"""

# Extracting genres frrom listed_in column
genres = Netflix_data['listed_in'].str.split(', ').explode()
top_genres = genres.value_counts().head(10)
print("Top 10 Genres:")
print(top_genres)

# Visualize top 10 genres
plt.figure(figsize=(12, 6))
sns.barplot(x=top_genres.index, y=top_genres.values, palette='viridis', hue=top_genres.index, legend=False)
plt.title('Top 10 Genres on Netflix')
plt.xlabel('Genre')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Identify and count the most frequent countries
countries = Netflix_data['country'].str.split(', ').explode()
top_countries = countries.value_counts().head(10)
print("Top 10 Countries:")
print(top_countries)

# Visualize top 10 countries
plt.figure(figsize=(12, 6))
sns.barplot(x=top_countries.index, y=top_countries.values, palette='viridis', hue=top_countries.index, legend=False)
plt.title('Top 10 Countries on Netflix')
plt.xlabel('Country')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

# Identify and count the most frequent directors
top_directors = Netflix_data['director'].value_counts().head(10)
print("Top 10 Directors:")
print(top_directors)

# Visualize top 10 directors
plt.figure(figsize=(12, 6))
sns.barplot(x=top_directors.index, y=top_directors.values, palette='viridis', hue=top_directors.index, legend=False)
plt.title('Top 10 Directors on Netflix')
plt.xlabel('Director')
plt.ylabel('Number of Titles')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

"""## Final Task


Summarize the key insights gained from the analysis and suggest potential next steps for further investigation.

## Summary:

### Data Analysis Key Findings

*   The dataset was clean, with no missing values or duplicate rows identified after initial checks. The 'duration' column was successfully parsed into numerical `duration_value` (e.g., 90 for 'min', 1 for 'Season') and `duration_unit` components for further analysis.
*   **Content Type Distribution:** Movies make up the majority of content on Netflix, accounting for 69.7% (6126 titles), while TV Shows represent 30.3% (2664 titles) of the content library.
*   **Temporal Trends:**
    *   The number of titles added to Netflix showed a significant increase over the years, indicating a substantial content acquisition strategy, especially in recent years.
    
*   **Content Ratings:**
    *   `TV-MA` is the most common content rating overall (3205 titles), followed by `TV-14` (2157 titles) and `TV-PG` (861 titles).
    *   Ratings such as `R`, `PG-13`, `PG`, and `G` are predominantly associated with Movies, while `TV-MA` is particularly dominant for TV Shows.
*   **Top Categories:**
    *   **Top Genres:** 'International Movies' (2752 titles), 'Dramas' (2426 titles), and 'Comedies' (1674 titles) are the most prevalent genres.
    *   **Top Countries:** The 'United States' (3240 titles), 'India' (1057 titles), and 'United Kingdom' (638 titles) are the leading countries in terms of content contribution.
    *   **Top Directors:** A significant portion of titles (2588) have no director information ('Not Given'). Among specified directors, 'Rajiv Chilaka' is the most prolific with 20 titles.

### Insights or Next Steps

*   **Content Strategy Focus:** Netflix's content strategy appears heavily skewed towards movies and mature/teen audiences (TV-MA, TV-14). This could indicate a strategic focus or a gap in content for younger audiences or specific movie ratings.
*   **Geographical Expansion:** While the US dominates, the high volume of 'International Movies' and content from India and the UK suggests a strong focus on global content acquisition.
"""